<?php

namespace Eliastre100\RoomsBundle\Entity;

/**
 * PlaylistMusicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistMusicsRepository extends \Doctrine\ORM\EntityRepository
{
}
